In [15]:
from tfrecordManager import tfrecordManager

#### Loads tfrecords for audio datasets in Patset.

In [16]:
tfr = tfrecordManager()

In [25]:
# Take a single record from a file
#filename = ["sampleDir/shard0.tfrecord"]
filename = ["sampleDir/DripPatternSynth--rate_exp-00.60--Irregularity-00.00--center_frequency-220.00--v-000.tfrecord"]
data_record = tfr.__printRecord__(filename[0])
data_record

features {
  feature {
    key: "audio"
    value {
      float_list {
        value: 0.0
        value: 0.10674727708101273
        value: 0.2126208245754242
        value: 0.31684064865112305
        value: 0.4186301529407501
        value: 0.5172311067581177
        value: 0.6119092106819153
        value: 0.7019597887992859
        value: 0.7867128849029541
        value: 0.8655381798744202
        value: 0.9378499388694763
        value: 1.0031111240386963
        value: 1.060837745666504
        value: 1.1106021404266357
        value: 1.1520359516143799
        value: 1.1848337650299072
        value: 1.2087544202804565
        value: 1.223623275756836
        value: 1.229333519935608
        value: 1.2258466482162476
        value: 1.2131932973861694
        value: 1.1914722919464111
        value: 1.1608506441116333
        value: 1.1215617656707764
        value: 1.0739036798477173
        value: 1.0182372331619263
        value: 0.954983115196228
        value: 0.88461858034

#### Load single records

In [26]:
# Get feature list as JSON
tfr.__getFeatures__(data_record)

[['rate_exp_synth_maxval', 'float_list'],
 ['cf', 'float_list'],
 ['cf_synth_units', 'bytes_list'],
 ['cf_user_minval', 'float_list'],
 ['cf_user_nvals', 'int64_list'],
 ['irreg_exp_synth_maxval', 'float_list'],
 ['irreg_exp_user_minval', 'float_list'],
 ['irreg_exp_synth_units', 'bytes_list'],
 ['soundDuration', 'float_list'],
 ['irreg_exp_synth_minval', 'float_list'],
 ['irreg_exp_user_nvals', 'int64_list'],
 ['cf_user_maxval', 'float_list'],
 ['rate_exp_user_minval', 'float_list'],
 ['segmentNum', 'int64_list'],
 ['audio', 'float_list'],
 ['cf_synth_minval', 'float_list'],
 ['cf_synth_maxval', 'float_list'],
 ['irreg_exp_user_maxval', 'float_list'],
 ['irreg_exp', 'float_list'],
 ['rate_exp_synth_minval', 'float_list'],
 ['rate_exp_synth_units', 'bytes_list'],
 ['rate_exp_user_nvals', 'int64_list'],
 ['rate_exp', 'float_list'],
 ['rate_exp_user_maxval', 'float_list'],
 ['pfname', 'bytes_list']]

In [27]:
# Use feature list to read serialized TFrecords
tfr.__readOne__(filename)

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.10674728, 0.21262082, ..., 0.        , 0.        ,
       0.        ], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([220.], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth

#### Loading tfrecords in a directory

In [24]:
# Provide a relative path to read a directory of TFrecords
tfdir = "sampleDir"
tfr.__readDirectory__(tfdir)

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([317.77777], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8888889], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth_minval': <tf.Tensor: shape=(1,), dtype=floa

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.17203194, 0.3407309 , ..., 0.        , 0.        ,
       0.        ], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([342.22223], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([415.55554], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11111111], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth_minval': <tf.Tensor: shape=(1,), dtype=flo

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , ..., 0.5382787 , 0.46295133,
       0.38227642], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([268.8889], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6666667], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irre

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([268.8889], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8888889], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth_minval': <tf.Tensor: shape=(1,), dtype=float

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , ..., 0.80333805, 0.8288489 ,
       0.8450395 ], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([268.8889], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.33333334], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irr